language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t intelligentappsofficial/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true intelligentappsofficial/react-test npm test

after_success:
  - docker build -t intelligentappsofficial/multi-client ./client 
  - docker build -t intelligentappsofficial/multi-nginx ./nginx 
  - docker build -t intelligentappsofficial/multi-server ./server 
  - docker build -t intelligentappsofficial/multi-worker ./worker 

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 

  - docker push intelligentappsofficial/multi-client
  - docker push intelligentappsofficial/multi-nginx
  - docker push intelligentappsofficial/multi-server
  - docker push intelligentappsofficial/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-625667287519'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY