language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t intellapps/react-test -f ./clieint/Dockerfile.dev

script:
  - docker run -e CI=true intellapps/react-test npm test

after_success:
  - docker build -t intellapps/multi-client ./client 
  - docker build -t intellapps/multi-nginx ./nginx 
  - docker build -t intellapps/multi-server ./server 
  - docker build -t intellapps/multi-worker ./worker 

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  
  - docker push intellapps/multi-client
  - docker push intellapps/multi-nginx
  - docker push intellapps/multi-server
  - docker push intellapps/multi-worker